from pathlib import Path
from typing import Protocol, Sequence


class ArtifactStore(Protocol):
    async def list_objects(self, prefix: str) -> Sequence[str]: ...

    async def download_object(self, storage_path: str, destination: Path) -> None: ...

    async def upload_object(self, source: Path, storage_path: str) -> None: ...

    async def copy_prefix(self, source_prefix: str, target_prefix: str) -> None: ...

    def object_uri(self, storage_path: str) -> str: ...
